<?xml version="1.0" encoding="utf-8"?><Database Name="coll" Class="DataClasses1DataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="WebSettings" ConnectionString="Data Source=SNAKEJAZZ\SQLEXPRESS;Initial Catalog=coll;Integrated Security=True" SettingsObjectName="System.Configuration.ConfigurationManager.ConnectionStrings" SettingsPropertyName="collConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.ajayk57_games" Member="ajayk57_games">
    <Type Name="ajayk57_game">
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="name" Type="System.String" DbType="VarChar(25) NOT NULL" CanBeNull="false" />
      <Column Name="is_outdoor" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="pcount" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.ajayk57_library" Member="ajayk57_libraries">
    <Type Name="ajayk57_library">
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="name" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="author" Type="System.String" DbType="VarChar(40)" CanBeNull="true" />
    </Type>
  </Table>
</Database>